/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppLogin {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
    interface ImagePreview {
        "image": any;
        "pred": any;
    }
    interface PopoverPage {
        "userAgent": any;
    }
    interface PredDetail {
        "data": any;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppLoginElement extends Components.AppLogin, HTMLStencilElement {
    }
    var HTMLAppLoginElement: {
        prototype: HTMLAppLoginElement;
        new (): HTMLAppLoginElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLImagePreviewElement extends Components.ImagePreview, HTMLStencilElement {
    }
    var HTMLImagePreviewElement: {
        prototype: HTMLImagePreviewElement;
        new (): HTMLImagePreviewElement;
    };
    interface HTMLPopoverPageElement extends Components.PopoverPage, HTMLStencilElement {
    }
    var HTMLPopoverPageElement: {
        prototype: HTMLPopoverPageElement;
        new (): HTMLPopoverPageElement;
    };
    interface HTMLPredDetailElement extends Components.PredDetail, HTMLStencilElement {
    }
    var HTMLPredDetailElement: {
        prototype: HTMLPredDetailElement;
        new (): HTMLPredDetailElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-login": HTMLAppLoginElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "image-preview": HTMLImagePreviewElement;
        "popover-page": HTMLPopoverPageElement;
        "pred-detail": HTMLPredDetailElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppLogin {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface ImagePreview {
        "image"?: any;
        "pred"?: any;
    }
    interface PopoverPage {
        "onLoggedOut"?: (event: CustomEvent<any>) => void;
        "userAgent"?: any;
    }
    interface PredDetail {
        "data"?: any;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-login": AppLogin;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "image-preview": ImagePreview;
        "popover-page": PopoverPage;
        "pred-detail": PredDetail;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-login": LocalJSX.AppLogin & JSXBase.HTMLAttributes<HTMLAppLoginElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "image-preview": LocalJSX.ImagePreview & JSXBase.HTMLAttributes<HTMLImagePreviewElement>;
            "popover-page": LocalJSX.PopoverPage & JSXBase.HTMLAttributes<HTMLPopoverPageElement>;
            "pred-detail": LocalJSX.PredDetail & JSXBase.HTMLAttributes<HTMLPredDetailElement>;
        }
    }
}
