/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppLogin {}
  interface AppLoginAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'name': string;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface ImagePreview {
    'image': Blob;
    'pred': any;
  }
  interface ImagePreviewAttributes extends StencilHTMLAttributes {
    'image'?: Blob;
    'pred'?: any;
  }

  interface PopoverPage {
    'userAgent': any;
  }
  interface PopoverPageAttributes extends StencilHTMLAttributes {
    'onLoggedOut'?: (event: CustomEvent) => void;
    'userAgent'?: any;
  }

  interface PredDetail {
    'data': any;
  }
  interface PredDetailAttributes extends StencilHTMLAttributes {
    'data'?: any;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppLogin': Components.AppLogin;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'ImagePreview': Components.ImagePreview;
    'PopoverPage': Components.PopoverPage;
    'PredDetail': Components.PredDetail;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-login': Components.AppLoginAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'image-preview': Components.ImagePreviewAttributes;
    'popover-page': Components.PopoverPageAttributes;
    'pred-detail': Components.PredDetailAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppLoginElement extends Components.AppLogin, HTMLStencilElement {}
  var HTMLAppLoginElement: {
    prototype: HTMLAppLoginElement;
    new (): HTMLAppLoginElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLImagePreviewElement extends Components.ImagePreview, HTMLStencilElement {}
  var HTMLImagePreviewElement: {
    prototype: HTMLImagePreviewElement;
    new (): HTMLImagePreviewElement;
  };

  interface HTMLPopoverPageElement extends Components.PopoverPage, HTMLStencilElement {}
  var HTMLPopoverPageElement: {
    prototype: HTMLPopoverPageElement;
    new (): HTMLPopoverPageElement;
  };

  interface HTMLPredDetailElement extends Components.PredDetail, HTMLStencilElement {}
  var HTMLPredDetailElement: {
    prototype: HTMLPredDetailElement;
    new (): HTMLPredDetailElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-login': HTMLAppLoginElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'image-preview': HTMLImagePreviewElement
    'popover-page': HTMLPopoverPageElement
    'pred-detail': HTMLPredDetailElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-login': HTMLAppLoginElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'image-preview': HTMLImagePreviewElement;
    'popover-page': HTMLPopoverPageElement;
    'pred-detail': HTMLPredDetailElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
